stages:
    - infracost
    - deploy

deploy-infracost:
    stage: infracost
    image: alpine:latest
    script:
        - apk add --no-cache curl
        - curl -sSL https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | sh
    script:
        - infracost breakdown --path=.
    tags:
        - bookstack-runner
    # rules:
    #     - if: $CI_COMMIT_BRANCH == "main"
    #       when: always

deploy-infra:
    stage: deploy
    image: hashicorp/terraform:latest
    variables:
        TF_IN_AUTOMATION: "true"  # Indique à Terraform qu'il tourne en CI
    script:
        - terraform init 
        - terraform fmt 
        - terraform validate
        - terraform plan -lock=false
        # - terraform apply -lock=false -auto-approve
    tags:
        - bookstack-runner
    # rules:
    #     - if: $CI_COMMIT_BRANCH == "main"
    #       when: always

