stages:
  - infracost
  - deploy

infracost-breakdown:
  stage: infracost
  script:
    # La commande est maintenant directe car le binaire est dans /usr/local/bin
    - infracost breakdown --path=. --format=json --out-file=infracost.json
    - infracost output --path infracost.json --format table
  tags:
    - bs-runner-2
#   rules:
#     - if: $CI_COMMIT_BRANCH == "main"

deploy-infrastructure:
  stage: deploy
  before_script:
    - echo $TF_HTTP_USERNAME
    - echo $TF_HTTP_PASSWORD
  script:
    - terraform init 
    - terraform fmt -check
    - terraform validate
    - terraform plan -lock=false -input=false
    # - terraform apply -auto-approve -lock=false
  tags:
    - bs-runner-2
#   rules:
#     - if: $CI_COMMIT_BRANCH == "main"