bdd-test:
  hosts:
    psql-test:
      ansible_host: "13.36.168.214"
      ansible_port: 22
      ansible_ssh_private_key_file: "/home/engineer/setup/test-BDD/grafana.pem"
      ansible_user: "ubuntu"