---
- name: Création des bases PostgreSQL via tunnel SSH
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
      rds_host: "shared-bookstack-keycloak-rds.crogwcggglt8.eu-north-1.rds.amazonaws.com"
      rds_port: 5432
      local_port: 5433

      db_user: "dbadmin"
      db_password: "{{ lookup('env', 'RDS_PASSWORD') }}"

      databases:
          - keycloak_prod
          - keycloak_staging
          - bookstack_prod
          - bookstack_staging

  tasks:
      - name: Ouvrir un tunnel SSH via swarm-master (ProxyJump bastion)
        command: >
            ssh -f -N
            -L {{ local_port }}:{{ rds_host }}:{{ rds_port }}
            swarm-master
        async: 10
        poll: 0

      - name: Attendre que le tunnel soit ouvert
        wait_for:
            host: "localhost"
            port: "{{ local_port }}"
            timeout: 10

      - name: Créer les bases PostgreSQL via psql
        command: >
            psql "host=localhost port={{ local_port }} user={{ db_user }} password={{ db_password }} sslmode=require"
            -c "CREATE DATABASE {{ item }};"
        loop: "{{ databases }}"
        ignore_errors: true
